name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  PROJECT_NAME: ReleaseManager/ReleaseManager.sln

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Display Node.js version
        run: node --version

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Display .NET version
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore $PROJECT_NAME

      - name: Build
        run: dotnet build $PROJECT_NAME --no-restore

      - name: Test
        run: dotnet test $PROJECT_NAME --no-build --verbosity normal



